#! /bin/sh -e

# grub-mkconfig helper script.
#
# Copyright © 2009 Stefan Lippers-Hollmann <s.l-h@gmx.de>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# override tool behaviour through /etc/default/grub2-fll-fromiso
FLL_GRUB2_ISO_LOCATION="/var/cache/pyfll"
FLL_GRUB2_ISO_PREFIX="sidux- fullstory-"
FLL_GRUB2_LANG="de_DE"
FLL_GRUB2_TZ="Europe/Berlin"
FLL_GRUB2_VGA="794"
FLL_GRUB2_CHEATCODE="quiet noeject screen=1400x1050 xrate=100"

# source overrides
[ -r /etc/default/grub2-fll-fromiso ] && . /etc/default/grub2-fll-fromiso

# find ISO
FROMISO="${FLL_GRUB2_ISO_LOCATION}/sidux-snapshot-kde-full-i386-amd64-200908230118.iso"

# assemble cmdline
CMDLINE="boot=fll vga=${FLL_GRUB2_VGA} lang=${FLL_GRUB2_LANG} TZ=${FLL_GRUB2_TZ} ${FLL_GRUB2_CHEATCODE} fromiso=${FROMISO}"
